<div class="row">
    <div class="col-md-6">
        <?php $this->beginContent('@app/views/layouts/_card_wrapper.php', [
            'title' => 'Login Security',
        ]) ?>
            <div class="form-group m-0">
                <label class="option">
                    <span class="option-control">
                        <span class="radio">
                            <input type="radio" name="m_option_1" value="1" checked="checked">
                            <span></span>
                        </span>
                    </span>
                    <span class="option-label">
                        <span class="option-head">
                            <span class="option-title">Account Password</span>
                            <!-- <span class="option-focus">Free</span> -->
                        </span>
                        <span class="option-body">Login using account given password.</span>
                    </span>
                </label>
                <label class="option">
                    <span class="option-control">
                        <span class="radio">
                            <input type="radio" name="m_option_1" value="1">
                            <span></span>
                        </span>
                    </span>
                    <span class="option-label">
                        <span class="option-head">
                            <span class="option-title">2 Factor Email Authentication</span>
                            <!-- <span class="option-focus">$&nbsp;8.00</span> -->
                        </span>
                        <span class="option-body">Login using your password with 2 factor email authentication code.</span>
                    </span>
                </label>
                <label class="option">
                    <span class="option-control">
                        <span class="radio">
                            <input type="radio" name="m_option_1" value="1">
                            <span></span>
                        </span>
                    </span>
                    <span class="option-label">
                        <span class="option-head">
                            <span class="option-title">Google Authenticator</span>
                            <!-- <span class="option-focus">$&nbsp;8.00</span> -->
                        </span>
                        <span class="option-body">Login using password generated by google authenticator app. Make sure to scan Google Athenticator QR Code.</span>
                    </span>
                </label>
            </div>
        <?php $this->endContent() ?>
    </div>    
</div>