<?php

namespace app\commands\seeder;

use app\commands\models\Country;
use yii\db\Expression;

class CountrySeeder extends Seeder
{
	public $modelClass = 'app\commands\models\Country';
    const DATA = [
        array(4, 'Afghanistan', 'AFG'),
        array(8, 'Albania', 'ALB'),
        array(12, 'Algeria', 'DZA'),
        array(16, 'American Samoa', 'ASM'),
        array(20, 'Andorra', 'AND'),
        array(24, 'Angola', 'AGO'),
        array(28, 'Antigua and Barbuda', 'ATG'),
        array(31, 'Azerbaijan', 'AZE'),
        array(32, 'Argentina', 'ARG'),
        array(36, 'Australia', 'AUS'),
        array(40, 'Austria', 'AUT'),
        array(44, 'Bahamas', 'BHS'),
        array(48, 'Bahrain', 'BHR'),
        array(50, 'Bangladesh', 'BGD'),
        array(51, 'Armenia', 'ARM'),
        array(52, 'Barbados', 'BRB'),
        array(56, 'Belgium', 'BEL'),
        array(60, 'Bermuda', 'BMU'),
        array(64, 'Bhutan', 'BTN'),
        array(68, 'Bolivia', 'BOL'),
        array(70, 'Bosnia and Herzegovina', 'BIH'),
        array(72, 'Botswana', 'BWA'),
        array(76, 'Brazil', 'BRA'),
        array(84, 'Belize', 'BLZ'),
        array(90, 'Solomon Islands', 'SLB'),
        array(92, 'British Virgin Islands', 'VGB'),
        array(96, 'Brunei Darussalam', 'BRN'),
        array(100, 'Bulgaria', 'BGR'),
        array(104, 'Myanmar', 'MMR'),
        array(108, 'Burundi', 'BDI'),
        array(112, 'Belarus', 'BLR'),
        array(116, 'Cambodia', 'KHM'),
        array(120, 'Cameroon', 'CMR'),
        array(124, 'Canada', 'CAN'),
        array(132, 'Cape Verde', 'CPV'),
        array(136, 'Cayman Islands', 'CYM'),
        array(140, 'Central African Republic', 'CAF'),
        array(144, 'Sri Lanka', 'LKA'),
        array(148, 'Chad', 'TCD'),
        array(152, 'Chile', 'CHL'),
        array(156, 'China', 'CHN'),
        array(158, 'Taiwan', 'TWN'),
        array(170, 'Colombia', 'COL'),
        array(174, 'Comoros', 'COM'),
        array(175, 'Mayotte', 'MYT'),
        array(178, 'Congo', 'COG'),
        array(180, 'Democratic Republic of the Congo', 'COD'),
        array(184, 'Cook Islands', 'COK'),
        array(188, 'Costa Rica', 'CRI'),
        array(191, 'Croatia', 'HRV'),
        array(192, 'Cuba', 'CUB'),
        array(196, 'Cyprus', 'CYP'),
        array(203, 'Czech Republic', 'CZE'),
        array(204, 'Benin', 'BEN'),
        array(208, 'Denmark', 'DNK'),
        array(212, 'Dominica', 'DMA'),
        array(214, 'Dominican Republic', 'DOM'),
        array(218, 'Ecuador', 'ECU'),
        array(222, 'El Salvador', 'SLV'),
        array(226, 'Equatorial Guinea', 'GNQ'),
        array(231, 'Ethiopia', 'ETH'),
        array(232, 'Eritrea', 'ERI'),
        array(233, 'Estonia', 'EST'),
        array(234, 'Faeroe Islands', 'FRO'),
        array(238, 'Falkland Islands (Malvinas)', 'FLK'),
        array(242, 'Fiji', 'FJI'),
        array(246, 'Finland', 'FIN'),
        array(248, 'Åland Islands', 'ALA'),
        array(250, 'France', 'FRA'),
        array(254, 'French Guiana', 'GUF'),
        array(258, 'French Polynesia', 'PYF'),
        array(262, 'Djibouti', 'DJI'),
        array(266, 'Gabon', 'GAB'),
        array(268, 'Georgia', 'GEO'),
        array(270, 'Gambia', 'GMB'),
        array(275, 'Occupied Palestinian Territory', 'PSE'),
        array(276, 'Germany', 'DEU'),
        array(288, 'Ghana', 'GHA'),
        array(292, 'Gibraltar', 'GIB'),
        array(296, 'Kiribati', 'KIR'),
        array(300, 'Greece', 'GRC'),
        array(304, 'Greenland', 'GRL'),
        array(308, 'Grenada', 'GRD'),
        array(312, 'Guadeloupe', 'GLP'),
        array(316, 'Guam', 'GUM'),
        array(320, 'Guatemala', 'GTM'),
        array(324, 'Guinea', 'GIN'),
        array(328, 'Guyana', 'GUY'),
        array(332, 'Haiti', 'HTI'),
        array(336, 'Holy See', 'VAT'),
        array(340, 'Honduras', 'HND'),
        array(344, 'Hong Kong Special Administrative Region of China', 'HKG'),
        array(348, 'Hungary', 'HUN'),
        array(352, 'Iceland', 'ISL'),
        array(356, 'India', 'IND'),
        array(360, 'Indonesia', 'IDN'),
        array(364, 'Iran (Islamic Republic of)', 'IRN'),
        array(368, 'Iraq', 'IRQ'),
        array(372, 'Ireland', 'IRL'),
        array(376, 'Israel', 'ISR'),
        array(380, 'Italy', 'ITA'),
        array(384, 'Côte d\'Ivoire', 'CIV'),
        array(388, 'Jamaica', 'JAM'),
        array(392, 'Japan', 'JPN'),
        array(398, 'Kazakhstan', 'KAZ'),
        array(400, 'Jordan', 'JOR'),
        array(404, 'Kenya', 'KEN'),
        array(408, 'Democratic People\'s Republic of Korea', 'PRK'),
        array(410, 'Republic of Korea', 'KOR'),
        array(414, 'Kuwait', 'KWT'),
        array(417, 'Kyrgyzstan', 'KGZ'),
        array(418, 'Lao People\'s Democratic Republic', 'LAO'),
        array(422, 'Lebanon', 'LBN'),
        array(426, 'Lesotho', 'LSO'),
        array(428, 'Latvia', 'LVA'),
        array(430, 'Liberia', 'LBR'),
        array(434, 'Libyan Arab Jamahiriya', 'LBY'),
        array(438, 'Liechtenstein', 'LIE'),
        array(440, 'Lithuania', 'LTU'),
        array(442, 'Luxembourg', 'LUX'),
        array(446, 'Macao Special Administrative Region of China', 'MAC'),
        array(450, 'Madagascar', 'MDG'),
        array(454, 'Malawi', 'MWI'),
        array(458, 'Malaysia', 'MYS'),
        array(462, 'Maldives', 'MDV'),
        array(466, 'Mali', 'MLI'),
        array(470, 'Malta', 'MLT'),
        array(474, 'Martinique', 'MTQ'),
        array(478, 'Mauritania', 'MRT'),
        array(480, 'Mauritius', 'MUS'),
        array(484, 'Mexico', 'MEX'),
        array(492, 'Monaco', 'MCO'),
        array(496, 'Mongolia', 'MNG'),
        array(498, 'Republic of Moldova', 'MDA'),
        array(499, 'Montenegro', 'MNE'),
        array(500, 'Montserrat', 'MSR'),
        array(504, 'Morocco', 'MAR'),
        array(508, 'Mozambique', 'MOZ'),
        array(512, 'Oman', 'OMN'),
        array(516, 'Namibia', 'NAM'),
        array(520, 'Nauru', 'NRU'),
        array(524, 'Nepal', 'NPL'),
        array(528, 'Netherlands', 'NLD'),
        array(530, 'Netherlands Antilles', 'ANT'),
        array(533, 'Aruba', 'ABW'),
        array(540, 'New Caledonia', 'NCL'),
        array(548, 'Vanuatu', 'VUT'),
        array(554, 'New Zealand', 'NZL'),
        array(558, 'Nicaragua', 'NIC'),
        array(562, 'Niger', 'NER'),
        array(566, 'Nigeria', 'NGA'),
        array(570, 'Niue', 'NIU'),
        array(574, 'Norfolk Island', 'NFK'),
        array(578, 'Norway', 'NOR'),
        array(580, 'Northern Mariana Islands', 'MNP'),
        array(583, 'Micronesia (Federated States of)', 'FSM'),
        array(584, 'Marshall Islands', 'MHL'),
        array(585, 'Palau', 'PLW'),
        array(586, 'Pakistan', 'PAK'),
        array(591, 'Panama', 'PAN'),
        array(598, 'Papua New Guinea', 'PNG'),
        array(600, 'Paraguay', 'PRY'),
        array(604, 'Peru', 'PER'),
        array(608, 'Philippines', 'PHL'),
        array(612, 'Pitcairn', 'PCN'),
        array(616, 'Poland', 'POL'),
        array(620, 'Portugal', 'PRT'),
        array(624, 'Guinea-Bissau', 'GNB'),
        array(626, 'Timor-Leste', 'TLS'),
        array(630, 'Puerto Rico', 'PRI'),
        array(634, 'Qatar', 'QAT'),
        array(638, 'Réunion', 'REU'),
        array(642, 'Romania', 'ROU'),
        array(643, 'Russian Federation', 'RUS'),
        array(646, 'Rwanda', 'RWA'),
        array(652, 'Saint-Barthélemy', 'BLM'),
        array(654, 'Saint Helena', 'SHN'),
        array(659, 'Saint Kitts and Nevis', 'KNA'),
        array(660, 'Anguilla', 'AIA'),
        array(662, 'Saint Lucia', 'LCA'),
        array(666, 'Saint Pierre and Miquelon', 'SPM'),
        array(670, 'Saint Vincent and the Grenadines', 'VCT'),
        array(674, 'San Marino', 'SMR'),
        array(678, 'Sao Tome and Principe', 'STP'),
        array(682, 'Saudi Arabia', 'SAU'),
        array(686, 'Senegal', 'SEN'),
        array(688, 'Serbia', 'SRB'),
        array(690, 'Seychelles', 'SYC'),
        array(694, 'Sierra Leone', 'SLE'),
        array(702, 'Singapore', 'SGP'),
        array(703, 'Slovakia', 'SVK'),
        array(704, 'Viet Nam', 'VNM'),
        array(705, 'Slovenia', 'SVN'),
        array(706, 'Somalia', 'SOM'),
        array(710, 'South Africa', 'ZAF'),
        array(716, 'Zimbabwe', 'ZWE'),
        array(724, 'Spain', 'ESP'),
        array(732, 'Western Sahara', 'ESH'),
        array(736, 'Sudan', 'SDN'),
        array(740, 'Suriname', 'SUR'),
        array(744, 'Svalbard and Jan Mayen Islands', 'SJM'),
        array(748, 'Swaziland', 'SWZ'),
        array(752, 'Sweden', 'SWE'),
        array(756, 'Switzerland', 'CHE'),
        array(760, 'Syrian Arab Republic', 'SYR'),
        array(762, 'Tajikistan', 'TJK'),
        array(764, 'Thailand', 'THA'),
        array(768, 'Togo', 'TGO'),
        array(772, 'Tokelau', 'TKL'),
        array(776, 'Tonga', 'TON'),
        array(780, 'Trinidad and Tobago', 'TTO'),
        array(784, 'United Arab Emirates', 'ARE'),
        array(788, 'Tunisia', 'TUN'),
        array(792, 'Turkey', 'TUR'),
        array(795, 'Turkmenistan', 'TKM'),
        array(796, 'Turks and Caicos Islands', 'TCA'),
        array(798, 'Tuvalu', 'TUV'),
        array(800, 'Uganda', 'UGA'),
        array(804, 'Ukraine', 'UKR'),
        array(807, 'The former Yugoslav Republic of Macedonia', 'MKD'),
        array(818, 'Egypt', 'EGY'),
        array(826, 'United Kingdom of Great Britain and Northern Irela', 'GBR'),
        array(830, 'Channel Islands', '[No'),
        array(831, 'Guernsey', 'GGY'),
        array(832, 'Jersey', 'JEY'),
        array(833, 'Isle of Man', '[No'),
        array(834, 'United Republic of Tanzania', 'TZA'),
        array(840, 'United States of America', 'USA'),
        array(850, 'United States Virgin Islands', 'VIR'),
        array(854, 'Burkina Faso', 'BFA'),
        array(858, 'Uruguay', 'URY'),
        array(860, 'Uzbekistan', 'UZB'),
        array(862, 'Venezuela (Bolivian Republic of)', 'VEN'),
        array(876, 'Wallis and Futuna Islands', 'WLF'),
        array(882, 'Samoa', 'WSM'),
        array(887, 'Yemen', 'YEM'),
        array(894, 'Zambia', 'ZMB')
    ];

	public function attributes($key)
	{
        list($no, $name, $alpha_code) = self::DATA[$key - 1];
		return [
            'no' => $no,
            'name' => $name,
            'alpha_code' => $alpha_code,
            'created_at' => new Expression('UTC_TIMESTAMP'),
            'updated_at' => new Expression('UTC_TIMESTAMP'),
		];
	}
}